import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const packageDirectory = path.resolve(scriptDirectory, "..");
const sourceDirectory = path.join(packageDirectory, "src");
const componentsDirectory = path.join(sourceDirectory, "components");
const check = process.argv.includes("--check");

const componentDirectories = (await readdir(componentsDirectory, { withFileTypes: true }))
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const indexSource = `"use client";

/**
 * @alchyx/react — the Alchyx component library.
 *
 * This file is generated by scripts/generate-entries.mjs.
 */

import "./index.css";

export * from "./lib";
export * from "./theme";

${componentDirectories.map((directory) => `export * from "./components/${directory}";`).join("\n")}
`;

const cssImports = [];
for (const directory of componentDirectories) {
  const files = await readdir(path.join(componentsDirectory, directory));
  for (const fileName of files.filter((fileName) => fileName.endsWith(".css")).sort()) {
    cssImports.push(`@import "./components/${directory}/${fileName}";`);
  }
}

const cssSource = `/* Generated by scripts/generate-entries.mjs. */
${cssImports.join("\n")}
`;

const outputs = [
  [path.join(sourceDirectory, "index.ts"), indexSource],
  [path.join(sourceDirectory, "index.css"), cssSource],
];

let stale = false;
for (const [filePath, expected] of outputs) {
  if (check) {
    const actual = await readFile(filePath, "utf8").catch(() => "");
    if (actual !== expected) {
      console.error(`${path.relative(packageDirectory, filePath)} is stale. Run pnpm generate.`);
      stale = true;
    }
  } else {
    await writeFile(filePath, expected);
  }
}

if (stale) process.exitCode = 1;
